title: Hoeness - GoMinze
description: >
  Eine Stimmungsbarometer-WebApp
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gominze.github.io/hoeness" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
collections:
  - projects

markdown: kramdown

sass:
  style: compressed
