name: Build Docs

on:
  workflow_dispatch
  #push: {}
  #pull_request:
  #  types: [opened, synchronize]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.owner.login != 'Shopify'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.1'
        bundler-cache: true
    - run: bundle exec jekyll build --trace
